EfGumshoe.ExampleWebApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EfGumshoe.ExampleWebApp.Pages;



[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;


    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }


    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

EfGumshoe.ExampleWebApp/Pages/Index.cshtml.cs
using EfGumshoe.ExampleWebApp.Shared.ExampleQueries;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EfGumshoe.ExampleWebApp.Pages;



public class IndexModel : PageModel
{
    public IndexModel(
        ISyncQuery syncQuery,
        ITwoQueriesInSameContext twoQueriesInSameContext,
        ITransactionExampleQuery transactionExampleQuery
    )
    {
        ExampleQueries =
            new Dictionary<int, Func<CancellationToken, Task>>
            {
                [0] = syncQuery.Execute,
                [1] = twoQueriesInSameContext.ExecuteQueryAsync,
                [2] = transactionExampleQuery.ExecuteQueriesInTransactionAsync
            };
    }



    public Dictionary<int, Func<CancellationToken, Task>> ExampleQueries { get; set; }

    public Dictionary<int, string> QueryNames { get; } = new()
    {
        [0] = "Synchronous query",
        [1] = "2 queries in same context",
        [2] = "Multiple transactions"
    };

    public string Message { get; set; } = "Initial Request";



    public async Task OnPostRunQuery(int id, CancellationToken cancellationToken)
    {
        await ExampleQueries[id].Invoke(cancellationToken);
        Message = $"Query {id} executed";
    }
}

EfGumshoe.ExampleWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EfGumshoe.ExampleWebApp.Pages;



public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;


    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }


    public void OnGet()
    {
    }
}

EfGumshoe.ExampleWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <div class="row">
        @foreach (var queryId in Model.ExampleQueries.Keys)
        {
            <div class="col-lg-1">
                <form asp-page-handler="runQuery" method="post">
                    <button>@(Model.QueryNames[queryId])</button>
                    <input type="hidden" name="id" value="@queryId"/>
                </form>
            </div>
        }
    </div>
    <h3 class="clearfix">@Model.Message</h3>
</div>

EfGumshoe.ExampleWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EfGumshoe.ExampleWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/EfGumshoe.ExampleWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">EfGumshoe.ExampleWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - EfGumshoe.ExampleWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>